apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ticketing-was-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ticketing-was-deploy  # 대시 없이 바로 이름을 씁니다.
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
