apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-http-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
    
    # [기본 WAF 켜두기]
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"

    # 💡 [진짜 무조건 막히는 입구컷 설정]
    # URL에 악성 패턴이 보이면 ModSecurity를 거치기도 전에 Nginx가 403 에러 페이지를 냅다 던집니다. (사진과 똑같이 나옵니다!)
    nginx.ingress.kubernetes.io/server-snippet: |
      if ($request_uri ~* "(%3Cscript|<script|1=1|%27%20OR|' OR|UNION.*SELECT)") {
          return 403;
      }

    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service: { name: ticket-backend-svc, port: { number: 8000 } }
      - path: /
        pathType: Prefix
        backend:
          service: { name: ticket-frontend-svc, port: { number: 80 } }
