apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.6
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          value: "1234"
        - name: MARIADB_DATABASE
          value: "ticket"
        args:
          - "--character-set-server=utf8mb4"
          - "--collation-server=utf8mb4_unicode_ci"
          - "--skip-character-set-client-handshake"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/mysql/mariadb.conf.d
      volumes:
      - name: config-volume
        configMap:
          name: mysql-config
          items:
          - key: my.cnf
            path: server.cnf
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
