apiVersion: v1
kind: ResourceQuota
metadata:
  name: ticketing-quota
  namespace: ticketing-system # 전용 네임스페이스 권장
spec:
  hard:
    requests.cpu: "2"        # 조금 더 여유 있게 (HPA 고려)
    requests.memory: "4Gi"   
    limits.cpu: "4"          
    limits.memory: "6Gi"     
    pods: "20"               # Istio 사이드카가 생기면 파드 수가 늘어날 수 있음
    services: "10"           # 서비스 개수도 제한하여 무분별한 노드포트 생성 방지
