apiVersion: v1
kind: PersistentVolume
metadata:
  name: was-nfs-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: was-nfs
  nfs:
    server: 10.16.0.151  # [필수 확인] 실제 NFS 서버의 IP가 맞는지 확인 후 수정하세요!
    path: /root/ProjectWebPage/ProjectWebPage/dynamic # [권장] 가능하면 /root 하위가 아닌 일반 디렉토리를 공유하세요.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: was-nfs-pvc
spec:
  storageClassName: was-nfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
