apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-was-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ticketing-was
  template:
    metadata:
      labels:
        app: ticketing-was
    spec:
      containers:
      - name: ticketing-was
        image: kingking4105/ticketing-was:latest
        imagePullPolicy: Always
        workingDir: /app
        env:
        - name: DB_HOST
          value: "mysql-service"
        ports:
        - containerPort: 8000
        env:
        - name: TURNSTILE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: captcha-secret
              key: turnstile-key
        volumeMounts:
        - name: was-storage
          #mountPath: /app/data
          mountPath: /app
      volumes:
      - name: was-storage
        persistentVolumeClaim:
          claimName: was-nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ticketing-was-service
spec:
  type: LoadBalancer
  selector:
    app: ticketing-was
  ports:
  - port: 80
    targetPort: 8000
