apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-was-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-was
  template:
    metadata:
      labels:
        app: ticketing-was
    spec:
      containers:
      - name: ticketing-was
        image: kingking4105/ticketing-was:latest
        imagePullPolicy: Always
        workingDir: /app
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: TURNSTILE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: captcha-secret
              key: turnstile-key
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "100m"      # HPA 계산을 위한 기준점 (꼭 필요!)
            memory: "128Mi"
          limits:
            cpu: "500m"      # 최대 사용량 제한
            memory: "256Mi"
