# Dockerfile.web
FROM nginx:alpine

# 기본 설정 파일 삭제 및 덮어쓰기
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf

# 기존 웹 파일 삭제 및 복사
RUN rm -rf /usr/share/nginx/html/*
COPY ./NfsWebFile-main /usr/share/nginx/html/
RUN chmod -R 755 /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]