apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: db-nfs
  nfs:
    server: 10.16.0.151   # Rocky 9 NFS 서버 IP
    path: /root/ProjectWebPage/ProjectWebPage 
